site_name: MicroData

repo_name: "2024.2-T03-MicroData"
repo_url: "https://github.com/mdsreq-fga-unb/2024.2-T03-MicroData"

theme:
  name: material

nav: 
  - Intrudução: index.md
  - Visão do Produto e Projeto:
    - Visão do Produto: visao_produto_projeto/visao_do_produto.md

